#ifndef SWIFTSHADER_SHADER_COMPILER_ANALYSIS_HPP_
#define SWIFTSHADER_SHADER_COMPILER_ANALYSIS_HPP_

#include "ShaderCompiler/ShaderCompilerAnalysis.hpp"

#endif  // SWIFTSHADER_SHADER_COMPILER_ANALYSIS_HPP_
