#pragma once

#ifndef SWIFTSHADER_ENABLE_CUSTOM_GPU_BACKEND
#define SWIFTSHADER_ENABLE_CUSTOM_GPU_BACKEND 0
#endif

#ifndef SWIFTSHADER_CUSTOM_GPU_USE_CUDA
#define SWIFTSHADER_CUSTOM_GPU_USE_CUDA 0
#endif
