import("../swiftshader.gni")

swiftshader_source_set("Backend_headers") {
  sources = [
    "BackendConfig.hpp",
    "BackendFactory.hpp",
    "ExecutionBackend.hpp",
  ]
}

swiftshader_source_set("Backend") {
  sources = [
    "BackendFactory.cpp",
    "ExecutionBackend.cpp",
  ]

  deps = [
    "../System:System_headers",
  ]

  public_deps = [ ":Backend_headers" ]
}
