import("../swiftshader.gni")

swiftshader_source_set("Backend_headers") {
  sources = [
    "BackendConfig.hpp",
    "ComputeExecutable.hpp",
    "GraphicsExecutable.hpp",
    "BackendFactory.hpp",
    "StubRuntimeAPI.hpp",
    "FragmentBootstrap.hpp",
    "GraphicsDraw.hpp",
    "GraphicsBackend.hpp",
    "GraphicsBootstrap.hpp",
    "RasterBootstrap.hpp",
    "TriangleBootstrapDraw.hpp",
    "TrianglePipelineBootstrap.hpp",
    "PresentAdapter.hpp",
    "ExecutionBackend.hpp",
    "ResourceStateTracker.hpp",
    "RuntimeAPI.hpp",
  ]
}

swiftshader_source_set("Backend") {
  sources = [
    "BackendFactory.cpp",
    "ComputeExecutable.cpp",
    "GraphicsExecutable.cpp",
    "GpuExecutionBackend.cpp",
    "CpuExecutionBackend.cpp",
    "StubRuntimeAPI.cpp",
    "GraphicsDraw.cpp",
    "GraphicsBackend.cpp",
    "GraphicsBootstrap.cpp",
    "RasterBootstrap.cpp",
    "TriangleBootstrapDraw.cpp",
    "TrianglePipelineBootstrap.cpp",
    "PresentAdapter.cpp",
    "ExecutionBackend.cpp",
    "ExecutionBackendFactory.cpp",
    "ResourceStateTracker.cpp",
    "RuntimeAPI.cpp",
  ]

  deps = [
    "../Pipeline",
    "../System:System_headers",
  ]

  public_deps = [ ":Backend_headers" ]
}
